min_acceptable_rt_loop_frequency: 990.0

halt_on_slow_rt_loop: false

publish_every_rt_jitter: false

using_raspberry_pi: true

using_jetson_tx1: false

muscle_list:
  - name: r_pectoralis_major
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 3
    pressure_controller_channel: 0
    tension_controller_port: 5
    tension_controller_channel: 0
  - name: r_deltoid
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 3
    pressure_controller_channel: 1
    tension_controller_port: 5
    tension_controller_channel: 1
  - name: r_triceps_brachii
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 0
    pressure_controller_port: 3
    pressure_controller_channel: 2
    tension_controller_port: 5
    tension_controller_channel: 2
  - name: r_biceps_brachii
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 15
    pressure_controller_port: 3
    pressure_controller_channel: 4
    tension_controller_port: 5
    tension_controller_channel: 3
  - name: r_brachialis
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 7
    pressure_controller_port: 4
    pressure_controller_channel: 0
    tension_controller_port: 6
    tension_controller_channel: 0
  - name: r_brachioradialis
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 0
    pressure_controller_port: 4
    pressure_controller_channel: 1
    tension_controller_port: 6
    tension_controller_channel: 1
  - name: r_flexor_carpi_ulnaris
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 4
    pressure_controller_channel: 2
    tension_controller_port: 6
    tension_controller_channel: 2
  - name: r_extensor_digitorum
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 4
    pressure_controller_channel: 3
    tension_controller_port: 6
    tension_controller_channel: 3
