min_acceptable_rt_loop_frequency: 990.0

halt_on_slow_rt_loop: false

publish_every_rt_jitter: false

using_raspberry_pi: true

muscle_list:
  - name: humerus0
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 3
    pressure_controller_channel: 0
    tension_controller_port: 5
    tension_controller_channel: 0
  - name: ulna0
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 3
    pressure_controller_channel: 1
    tension_controller_port: 5
    tension_controller_channel: 1
  - name: humerus1
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 0
    pressure_controller_port: 3
    pressure_controller_channel: 2
    tension_controller_port: 5
    tension_controller_channel: 2
  - name: ulna1
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 15
    pressure_controller_port: 3
    pressure_controller_channel: 4
    tension_controller_port: 5
    tension_controller_channel: 3
  - name: humerus2
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 7
    pressure_controller_port: 4
    pressure_controller_channel: 0
    tension_controller_port: 6
    tension_controller_channel: 0
  - name: ulna2
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 0
    pressure_controller_port: 4
    pressure_controller_channel: 1
    tension_controller_port: 6
    tension_controller_channel: 1
  - name: humerus3
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 4
    pressure_controller_channel: 2
    tension_controller_port: 6
    tension_controller_channel: 2
  - name: ulna3
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 4
    pressure_controller_channel: 3
    tension_controller_port: 6
    tension_controller_channel: 3
