min_acceptable_rt_loop_frequency: 490.0

halt_on_slow_rt_loop: false

publish_every_rt_jitter: false

platform: "linux_platform" #[raspberry_pi, linux_platform, tinkerboard, dummy]

muscle_list:
  - name: muscle_1
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 0
    pressure_controller_port: 7
    pressure_controller_channel: 0
    tension_controller_port: 4
    tension_controller_channel: 0
  - name: muscle_2
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 2
    pressure_controller_port: 7
    pressure_controller_channel: 1
    tension_controller_port: 4
    tension_controller_channel: 1
  - name: muscle_3
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 2
    pressure_controller_port: 7
    pressure_controller_channel: 2
    tension_controller_port: 4
    tension_controller_channel: 2
  - name: muscle_4
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 3
    pressure_controller_port: 7
    pressure_controller_channel: 3
    tension_controller_port: 4
    tension_controller_channel: 3
  - name: muscle_5
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 4
    pressure_controller_port: 7
    pressure_controller_channel: 4
    tension_controller_port: 4
    tension_controller_channel: 4
  - name: muscle_6
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 5
    pressure_controller_port: 7
    pressure_controller_channel: 5
    tension_controller_port: 4
    tension_controller_channel: 5
  - name: muscle_7
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 6
    pressure_controller_port: 7
    pressure_controller_channel: 6
    tension_controller_port: 4
    tension_controller_channel: 6
  - name: muscle_8
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 7
    pressure_controller_channel: 7
    tension_controller_port: 4
    tension_controller_channel: 7
  - name: muscle_9
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 8
    pressure_controller_port: 7
    pressure_controller_channel: 8
    tension_controller_port: 4
    tension_controller_channel: 8
  - name: muscle_10
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 9
    pressure_controller_port: 7
    pressure_controller_channel: 9
    tension_controller_port: 4
    tension_controller_channel: 9
  - name: muscle_11
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 10
    pressure_controller_port: 7
    pressure_controller_channel: 10
    tension_controller_port: 4
    tension_controller_channel: 10
  - name: muscle_12
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 11
    pressure_controller_port: 7
    pressure_controller_channel: 11
    tension_controller_port: 4
    tension_controller_channel: 11
  - name: muscle_13
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 12
    pressure_controller_port: 7
    pressure_controller_channel: 12
    tension_controller_port: 4
    tension_controller_channel: 12
  - name: muscle_14
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 13
    pressure_controller_port: 7
    pressure_controller_channel: 13
    tension_controller_port: 4
    tension_controller_channel: 13
  - name: muscle_15
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 14
    pressure_controller_port: 7
    pressure_controller_channel: 14
    tension_controller_port: 4
    tension_controller_channel: 14
  - name: muscle_16
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 7
    pressure_controller_channel: 15
    tension_controller_port: 4
    tension_controller_channel: 15
  - name: muscle_17
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 14
    pressure_controller_port: 6
    pressure_controller_channel: 0
    tension_controller_port: 5
    tension_controller_channel: 0
  - name: muscle_18
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 1
    pressure_controller_port: 6
    pressure_controller_channel: 1
    tension_controller_port: 5
    tension_controller_channel: 1
  - name: muscle_19
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 1
    pressure_controller_port: 6
    pressure_controller_channel: 2
    tension_controller_port: 5
    tension_controller_channel: 2
  - name: muscle_20
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 3
    pressure_controller_port: 6
    pressure_controller_channel: 3
    tension_controller_port: 5
    tension_controller_channel: 3
  - name: muscle_21
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 4
    pressure_controller_port: 6
    pressure_controller_channel: 4
    tension_controller_port: 5
    tension_controller_channel: 4
  - name: muscle_22
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 5
    pressure_controller_port: 6
    pressure_controller_channel: 5
    tension_controller_port: 5
    tension_controller_channel: 5
  - name: muscle_23
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 6
    pressure_controller_port: 6
    pressure_controller_channel: 6
    tension_controller_port: 5
    tension_controller_channel: 6
  - name: muscle_24
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 10
    pressure_controller_port: 6
    pressure_controller_channel: 7
    tension_controller_port: 5
    tension_controller_channel: 7
  - name: muscle_25
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 8
    pressure_controller_port: 6
    pressure_controller_channel: 8
    tension_controller_port: 5
    tension_controller_channel: 8
  - name: muscle_26
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 9
    pressure_controller_port: 6
    pressure_controller_channel: 9
    tension_controller_port: 5
    tension_controller_channel: 9
  - name: muscle_27
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 6
    pressure_controller_channel: 10
    tension_controller_port: 5
    tension_controller_channel: 10
  - name: muscle_28
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 11
    pressure_controller_port: 6
    pressure_controller_channel: 11
    tension_controller_port: 5
    tension_controller_channel: 11
  - name: muscle_29
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 12
    pressure_controller_port: 6
    pressure_controller_channel: 12
    tension_controller_port: 5
    tension_controller_channel: 12
  - name: muscle_30
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 13
    pressure_controller_port: 6
    pressure_controller_channel: 13
    tension_controller_port: 5
    tension_controller_channel: 13
  - name: muscle_31
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 0
    pressure_controller_port: 6
    pressure_controller_channel: 14
    tension_controller_port: 5
    tension_controller_channel: 14
  - name: muscle_32
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 6
    pressure_controller_channel: 15
    tension_controller_port: 5
    tension_controller_channel: 15
